import { icons } from "./icons";

export const tabs: AppTab[] = [
    { name: "index",   title: "Home",       icon: icons.home },
    { name: "search",  title: "Search",     icon: icons.binocular },
    { name: "order",   title: "Order",      icon: icons.receipts },
    { name: "support", title: "Support",    icon: icons.headphone },
    { name: "profile", title: "Profile",    icon: icons.user }
];

export const HOME_USER = { name: "Joshua" };

export const HOME_BALANCE = {
    amount: 8489.48,
    nextRenewalDate: "2026-03-18T09:00:00.000Z",
};

export const UPCOMING_SUBSCRIPTIONS: UpcomingSubscription[] = [
    {
        id: "spotify",
        icon: icons.spotify,
        name: "Spotify",
        price: 5.99,
        currency: "USD",
        daysLeft: 2,
    },
    {
        id: "notion",
        icon: icons.notion,
        name: "Notion",
        price: 12.0,
        currency: "USD",
        daysLeft: 4,
    },
    {
        id: "figma",
        icon: icons.figma,
        name: "Figma",
        price: 15.0,
        currency: "USD",
        daysLeft: 6,
    },
];

export const HOME_SUBSCRIPTIONS: Subscription[] = [
    {
        id: "adobe-creative-cloud",
        icon: icons.adobe,
        name: "Adobe Creative Cloud",
        plan: "Teams Plan",
        category: "Design",
        paymentMethod: "Visa ending in 8530",
        status: "active",
        startDate: "2025-03-20T10:00:00.000Z",
        price: 77.49,
        currency: "USD",
        billing: "Monthly",
        renewalDate: "2026-03-20T10:00:00.000Z",
        color: "#f5c542",
    },
    {
        id: "github-pro",
        icon: icons.github,
        name: "GitHub Pro",
        plan: "Developer",
        category: "Developer Tools",
        paymentMethod: "Mastercard ending in 2408",
        status: "active",
        startDate: "2024-11-24T10:00:00.000Z",
        price: 9.99,
        currency: "USD",
        billing: "Monthly",
        renewalDate: "2026-03-24T10:00:00.000Z",
        color: "#e8def8",
    },
    {
        id: "claude-pro",
        icon: icons.claude,
        name: "Claude Pro",
        plan: "Pro Plan",
        category: "AI Tools",
        paymentMethod: "Amex ending in 1010",
        status: "paused",
        startDate: "2025-06-27T10:00:00.000Z",
        price: 20.0,
        currency: "USD",
        billing: "Monthly",
        renewalDate: "2026-03-27T10:00:00.000Z",
        color: "#b8d4e3",
    },
    {
        id: "canva-pro",
        icon: icons.canva,
        name: "Canva Pro",
        plan: "Yearly Access",
        category: "Design",
        paymentMethod: "Visa ending in 7784",
        status: "cancelled",
        startDate: "2024-04-02T10:00:00.000Z",
        price: 119.99,
        currency: "USD",
        billing: "Yearly",
        renewalDate: "2026-04-02T10:00:00.000Z",
        color: "#b8e8d0",
    }
];
export const CATEGORIES: Category[] = [
    {
        id: "restaurants",
        name: "Restaurants",
        icon: icons.restaurant,
        slug: "restaurants",
        color: "bg-amber-100",
        textColor: "text-amber-800",
    },
    {
        id: "shops",
        name: "Shops",
        icon: icons.shop,
        slug: "shops",
        color: "bg-blue-100",
        textColor: "text-blue-800",
    },
    {
        id: "mall",
        name: "Mall",
        icon: icons.mall,
        slug: "mall",
        color: "bg-purple-100",
        textColor: "text-purple-800",
    },
    {
        id: "local",
        name: "Local",
        icon: icons.local,
        slug: "local",
        color: "bg-green-100",
        textColor: "text-green-800",
    },
    {
        id: "pharmacy",
        name: "Pharmacy",
        icon: icons.pharmacy,
        slug: "pharmacy",
        color: "bg-green-100",
        textColor: "text-green-800",
    },
    {
        id: "laundromat",
        name: "Laundromat",
        icon: icons.laundromat,
        slug: "laundromat",
        color: "bg-cyan-100",
        textColor: "text-cyan-800",
    },
    {
        id: "errand",
        name: "Send an Errand",
        icon: icons.logistics,
        slug: "send-an-errand",
        color: "bg-orange-100",
        textColor: "text-orange-800",
    },
];

export const RESTAURANTS: Restaurant[] = [
    {
        id: "tantalizer",
        path: "Tantalizer",
        name: "Tantalizer",
        imageUrl: "https://res.cloudinary.com/dvwccrxix/image/upload/v1788435477/Tantalizer.jpg",
        location: "Ajebandele",
        deliveryTime: "20-30 mins",
        deliveryFee: 500,
        description: "Popular Nigerian restaurant serving authentic local dishes.",
        isActive: true,
    },
    {
        id: "mr-biggs",
        path: "Mr-Biggs",
        name: "Mr Biggs",
        imageUrl: "https://res.cloudinary.com/dvwccrxix/image/upload/v1788452816/Mr-Bigg_s.png",
        location: "New era",
        deliveryTime: "15-25 mins",
        deliveryFee: 400,
        description: "Nigeria's favourite chicken chain.",
        isActive: true,
    },
    {
        id: "crunchy",
        path: "Crunchy",
        name: "Crunchy",
        imageUrl: "https://res.cloudinary.com/dvwccrxix/image/upload/v1788452826/Crunchies.webp",
        location: "Mayfair",
        deliveryTime: "20-35 mins",
        deliveryFee: 450,
        description: "Classic Nigerian fast food chain.",
        isActive: true,
    },
    {
        id: "captain-cook",
        path: "Captain-cook",
        name: "Captain Cook",
        imageUrl: "https://res.cloudinary.com/dvwccrxix/image/upload/v1788452820/Captain-Cook.png",
        location: "Mayfair",
        deliveryTime: "20-35 mins",
        deliveryFee: 450,
        description: "Classic Nigerian fast food chain.",
        isActive: true,
    },
    {
        id: "mama-put",
        path: "mama_put",
        name: "Mama Put",
        imageUrl: "https://res.cloudinary.com/dvwccrxix/image/upload/v1788533096/Egusi.jpg",
        location: "Fagbale",
        deliveryTime: "25-40 mins",
        deliveryFee: 500,
        description: "Authentic Nigerian bukka experience.",
        isActive: true,
    },
    {
        id: "ivory-bite",
        path: "ivory_bite",
        name: "Ivory Bite",
        imageUrl: "https://res.cloudinary.com/dvwccrxix/image/upload/v1788452792/Ivory-Bite.jpg",
        location: "Ibadan Road",
        deliveryTime: "15-25 mins",
        deliveryFee: 400,
        description: "Finger licking fast food experience.",
        isActive: true,
    },

];

export const LOCAL_MEALS: LocalMeal[] = [
    {
        id: '1',
        name: 'Jollof Rice & Chicken',
        price: 3500,
        location: 'Lagos Island',
        imageUrl: 'https://res.cloudinary.com/dvwccrxix/image/upload/v1788451696/Jollof-Rice.jpg',
    },
    {
        id: '2',
        name: 'Peppered Suya Platter',
        price: 4200,
        location: 'Victoria Island',
        imageUrl: 'https://res.cloudinary.com/dvwccrxix/image/upload/v1788451398/Suya.jpg',
    },
    {
        id: '3',
        name: 'Egusi Soup & Pounded Yam',
        price: 5000,
        location: 'Lekki Phase 1',
        imageUrl: 'https://res.cloudinary.com/dvwccrxix/image/upload/v1788451631/Pounded-Yam_Egusi.jpg',
    },
    {
        id: '4',
        name: 'Grilled Catfish & Chips',
        price: 6500,
        location: 'Ikoyi',
        imageUrl: 'https://res.cloudinary.com/dvwccrxix/image/upload/v1788451346/Grilled-Catfish.jpg',
    },
    {
        id: '5',
        name: 'Ofada Rice & Ayamase',
        price: 4000,
        location: 'Surulere',
        imageUrl: 'https://res.cloudinary.com/dvwccrxix/image/upload/v1788451346/Grilled-Catfish.jpg',
    },
    {
        id: '6',
        name: 'Asun & Plantain',
        price: 3800,
        location: 'Yaba',
        imageUrl: 'https://res.cloudinary.com/dvwccrxix/image/upload/v1788451313/Asun-Plantain.jpg',
    },
];

export const CONTINENTAL_MEALS: ContinentalMeal[] = [
    {
        id: '1',
        name: 'Grilled Chicken & Mash',
        price: 5500,
        location: 'Victoria Island',
        imageUrl: 'https://res.cloudinary.com/dvwccrxix/image/upload/v1788451000/Grilled-Chicken-Mash.jpg',
    },
    {
        id: '2',
        name: 'Spaghetti Bolognese',
        price: 4800,
        location: 'Ikoyi',
        imageUrl: 'https://res.cloudinary.com/dvwccrxix/image/upload/v1788451000/Spaghetti-Bolognese.jpg',
    },
    {
        id: '3',
        name: 'Beef Steak & Fries',
        price: 6800,
        location: 'Lekki Phase 1',
        imageUrl: 'https://res.cloudinary.com/dvwccrxix/image/upload/v1788451000/Beef-Steak-Fries.jpg',
    },
    {
        id: '4',
        name: 'BBQ Ribs & Coleslaw',
        price: 7200,
        location: 'Ikeja GRA',
        imageUrl: 'https://res.cloudinary.com/dvwccrxix/image/upload/v1788451000/BBQ-Ribs-Coleslaw.jpg',
    },
    {
        id: '5',
        name: 'Chicken Alfredo Pasta',
        price: 5200,
        location: 'Surulere',
        imageUrl: 'https://res.cloudinary.com/dvwccrxix/image/upload/v1788451000/Chicken-Alfredo-Pasta.jpg',
    },
    {
        id: '6',
        name: 'Fish & Chips',
        price: 4500,
        location: 'Yaba',
        imageUrl: 'https://res.cloudinary.com/dvwccrxix/image/upload/v1788451000/Fish-and-Chips.jpg',
    },
];